### ISSUE TITLE
# Ticket Parent ## Feature: Stock Management (updating)

### ISSUE THREAD

**Issue by SandrineCipolla** [SandrineCipolla/StockHub#5]
**Scenario:** User update/manages a stock on the detailed stock page

Given the user is on the detailed view of a stock
When the user updates stock management with actions
Then the changes should be reflected in the stock details

- [ ] Implement Stock Quantity Update (related to #1)
- [ ] Implement Adding New Item to Stock (related to #2)
- [ ] Implement Removing Item from Stock (related to #3)

**Comment by SandrineCipolla** [comment]
- [ ] Implement Stock Quantity Update (related to https://github.com/SandrineCipolla/StockHub/issues/6 )
- [ ] Implement Adding New Item to Stock (related to https://github.com/SandrineCipolla/StockHub/issues/7 )
- [ ] Implement Removing Item from Stock (related to https://github.com/SandrineCipolla/StockHub/issues/8)
